eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
server:
  port: '8080'
spring:
  datasource:
    url: jdbc:postgresql://loyalty-postgres-db:5432/postgres
  data:
    mongodb:
      uri: mongodb://loyalty-mongo-db:27017/loyalty_service