axon:
  axonserver:
    enabled: 'false'
  eventhandling:
    processors:
      command-projection-group:
        mode: tracking
        dlq:
          enabled: true
      tracking:
        token-store:
          enabled: 'true'
          storage-token: 'true'
  eventstore:
    jdbc:
      initialize-schema: always # 'always' for Command API, 'never' for Query API
  saga:
    repository:
      type: jpa

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
server:
  port: '0'
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: loyalty-command-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/loyalty_service
      database: loyalty
      auto-index-creation: 'true'
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: 'true'
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  main:
    banner-mode: 'off'
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
